//! Snapshot test: the committed `docs/` directory is the canonical
//! markdown reference, generated by `cargo run -p xtask -- gen-md`.
//! Whenever the clap definitions or `cli/src/man.rs` extras change,
//! regenerate and commit. CI runs this test to catch the case where
//! someone forgets.
//!
//! On mismatch, the failure message names the offending file and tells
//! the reader exactly how to fix it. We don't print a full diff inline
//! to keep test output readable; reading the actual diff is one
//! `git diff docs/` away once the user runs the regen.
//!
//! The man pages don't get the same treatment — they're a build
//! artifact under `target/man/` and never committed, so there's
//! nothing to drift.

use std::collections::BTreeMap;

use tempfile::TempDir;

#[test]
fn docs_match_committed() {
    let tmp = TempDir::new().expect("tempdir");
    xtask::gen_md(tmp.path()).expect("gen_md");

    let workspace_root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("workspace root");
    // Generated reference pages live under `docs/cmds/`; the rest of
    // `docs/` is hand-authored (protocol specs, etc.) and not in scope.
    let docs = workspace_root.join("docs").join("cmds");

    let actual = read_dir_to_map(tmp.path());
    let committed = read_dir_to_map(&docs);

    let mut errors: Vec<String> = Vec::new();

    for (name, expected) in &actual {
        match committed.get(name) {
            None => errors.push(format!("docs/cmds/{name} is missing from the repo")),
            Some(found) if found != expected => {
                errors.push(format!("docs/cmds/{name} is out of date"));
            }
            _ => {}
        }
    }
    for name in committed.keys() {
        if !actual.contains_key(name) {
            errors.push(format!(
                "docs/cmds/{name} is committed but no longer generated; \
                 delete it"
            ));
        }
    }

    if !errors.is_empty() {
        let summary = errors.join("\n  ");
        panic!(
            "docs/cmds/ is out of sync with the clap definitions / \
             cli/src/man.rs.\n\
             \n  {summary}\n\n\
             Re-run `cargo run -p xtask -- gen-md` (or `just docs`) and commit \
             the result.",
        );
    }
}

fn read_dir_to_map(dir: &std::path::Path) -> BTreeMap<String, Vec<u8>> {
    let mut out = BTreeMap::new();
    let entries = match std::fs::read_dir(dir) {
        Ok(it) => it,
        Err(_) => return out,
    };
    for entry in entries.flatten() {
        if !entry.file_type().map(|t| t.is_file()).unwrap_or(false) {
            continue;
        }
        let name = entry.file_name().to_string_lossy().into_owned();
        if !name.ends_with(".md") {
            continue;
        }
        if let Ok(bytes) = std::fs::read(entry.path()) {
            out.insert(name, bytes);
        }
    }
    out
}
